<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AreaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('areas')->insert([
            ['name' => 'Hà Nội - Thị xã Sơn Tây', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Ba Đình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Cầu Giấy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Đống Đa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Hà Đông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Hai Bà Trưng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Hoàn Kiếm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Hoàng Mai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Long Biên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Tây Hồ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Thanh Xuân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Ba Vì', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Chương Mỹ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Đan Phượng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Đông Anh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Gia Lâm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Hoài Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Mê Linh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Mỹ Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Phúc Thọ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Quốc Oai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Sóc Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Thạch Thất', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Thanh Oai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Thanh Trì', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Thường Tín', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Bắc Từ Liêm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Huyện Ứng Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nội - Quận Nam Từ Liêm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 1', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 2', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 3', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 4', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 5', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 6', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 7', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 8', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 9', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 10', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 11', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận 12', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận Gò Vấp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận Tân Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận Tân Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận Bình Thạnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận Phú Nhuận', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận Thủ Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Quận Bình Tân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Huyện Củ Chi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Huyện Hóc Môn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Huyện Bình Chánh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Huyện Nhà Bè', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Huyện Cần Giờ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'TP Hồ Chí Minh - Thành phố Thủ Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Thành phố Long Xuyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Thành phố Châu Đốc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Thị xã Tân Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện An Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện Châu Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện Chợ Mới', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện Phú Tân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện Thoại Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện Tịnh Biên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'An Giang - Huyện Tri Tôn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Thành phố Vũng Tàu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Thành phố Bà Rịa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Huyện Long Điền', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Huyện Đất Đỏ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Huyện Châu Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Huyện Xuyên Mộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Huyện Côn Đảo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Thị xã Phú Mỹ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bà Rịa-Vũng Tàu - Huyện Long Đất', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Thành phố Bắc Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Hiệp Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Lạng Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Lục Nam', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Lục Ngạn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Sơn Động', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Tân Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Việt Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Yên Dũng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Huyện Yên Thế', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Giang - Thị xã Chũ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Thành Phố Bắc Kạn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Huyện Ba Bể', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Huyện Bạch Thông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Huyện Chợ Đồn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Huyện Chợ Mới', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Huyện Na Rì', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Huyện Ngân Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Kạn - Huyện Pác Nặm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bạc Liêu - Huyện Phước Long', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bạc Liêu - Huyện Hồng Dân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bạc Liêu - Huyện Vĩnh Lợi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bạc Liêu - Thị xã Giá Rai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bạc Liêu - Huyện Đông Hải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bạc Liêu - Huyện Hòa Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bạc Liêu - Thành phố Bạc Liêu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Thành phố Bắc Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Thành phố Từ Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Huyện Gia Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Huyện Lương Tài', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Huyện Quế Võ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Huyện Thuận Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Huyện Tiên Du', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bắc Ninh - Huyện Yên Phong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Thành phố Bến Tre', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Ba Tri', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Bình Đại', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Chợ Lách', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Giồng Trôm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Mỏ Cày Bắc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Mỏ Cày Nam', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bến Tre - Huyện Thạnh Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Thành phố Thủ Dầu Một', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Thị xã Bến Cát', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Huyện Dầu Tiếng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Huyện Bàu Bàng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Huyện Phú Giáo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Thị xã Tân Uyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Thành phố Dĩ An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Huyện Bắc Tân Uyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Dương - Thành phố Thuận An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Thành phố Quy Nhơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện An Lão', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Thị xã An Nhơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện Hoài Ân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Thị xã Hoài Nhơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện Phù Cát', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện Phù Mỹ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện Tuy Phước', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện Tây Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện Vân Canh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Định - Huyện Vĩnh Thạnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Thành phố Đồng Xoài', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Thị xã Bình Long', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Thị xã Phước Long', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Bù Đăng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Bù Đốp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Bù Gia Mập', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Chơn Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Đồng Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Hớn Quản', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Lộc Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Phước - Huyện Phú Riềng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Thành phố Phan Thiết', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Thị xã La Gi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện Tuy Phong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện Bắc Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện Hàm Thuận Bắc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện Hàm Thuận Nam', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện Tánh Linh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện Hàm Tân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện Đức Linh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bình Thuận - Huyện đảo Phú Quý', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Thành phố Cà Mau', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện Đầm Dơi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện Ngọc Hiển', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện Cái Nước', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện Trần Văn Thời', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện U Minh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện Thới Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện Năm Căn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cà Mau - Huyện Phú Tân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Thành phố Cao Bằng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Bảo Lạc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Bảo Lâm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Hạ Lang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Hà Quảng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Hòa An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Nguyên Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Phục Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Quảng Uyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Thạch An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Thông Nông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Trà Lĩnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Trùng Khánh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cao Bằng - Huyện Quảng Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Quận Ninh Kiều', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Quận Bình Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Quận Cái Răng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Quận Ô Môn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Quận Thốt Nốt', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Quận Hưng Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Huyện Phong Điền', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Huyện Cờ Đỏ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Huyện Thới Lai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Cần Thơ - Huyện Vĩnh Thạnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Quận Hải Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Quận Thanh Khê', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Quận Sơn Trà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Quận Ngũ Hành Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Quận Liên Chiểu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Quận Cẩm Lệ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Huyện Hòa Vang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đà Nẵng - Huyện đảo Hoàng Sa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Thành phố Buôn Ma Thuột', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Thị xã Buôn Hồ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Buôn Đôn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Cư Kuin', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Cư M\'gar', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Ea H\'leo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Ea Kar', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Ea Súp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Krông Bông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Krông Búk', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Krông Pắc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Lắk', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện M\'Đrắk', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Krông Ana', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Lắk - Huyện Krông Năng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Thành phố Gia Nghĩa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Huyện Cư Jút', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Huyện Đắk Glong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Huyện Đắk Mil', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Huyện Đắk R\'Lấp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Huyện Đắk Song', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Huyện Krông Nô', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đắk Nông - Huyện Tuy Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Thành phố Điện Biên Phủ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Thị xã Mường Lay', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Điện Biên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Điện Biên Đông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Mường Ảng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Mường Chà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Mường Nhé', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Tủa Chùa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Tuần Giáo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Điện Biên - Huyện Nậm Pồ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Thành phố Biên Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Thành phố Long Khánh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Định Quán', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Long Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Nhơn Trạch', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Tân Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Thống Nhất', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Vĩnh Cửu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Xuân Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Cẩm Mỹ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Nai - Huyện Trảng Bom', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Thành phố Cao Lãnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Thành phố Sa Đéc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Thành phố Hồng Ngự', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Cao Lãnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Hồng Ngự', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Lai Vung', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Lấp Vò', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Tam Nông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Tân Hồng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Thanh Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đồng Tháp - Huyện Tháp Mười', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Thành phố Pleiku', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Thị xã An Khê', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Thị xã Ayun Pa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Chư Păh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Chư Prông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Chư Sê', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Đăk Đoa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Đăk Pơ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Đức Cơ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Ia Grai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Ia Pa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện K\'Bang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Kông Chro', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Krông Pa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Mang Yang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Phú Thiện', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Gia Lai - Huyện Chư Pưh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Thành phố Hà Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Bắc Mê', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Bắc Quang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Đồng Văn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Hoàng Su Phì', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Mèo Vạc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Quản Bạ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Quang Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Vị Xuyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Xín Mần', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Giang - Huyện Yên Minh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nam - Thành phố Phủ Lý', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nam - Huyện Bình Lục', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nam - Thị xã Duy Tiên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nam - Huyện Kim Bảng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nam - Huyện Lý Nhân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Nam - Huyện Thanh Liêm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Thành phố Hà Tĩnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Thị xã Hồng Lĩnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Cẩm Xuyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Can Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Đức Thọ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Hương Khê', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Hương Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Kỳ Anh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Nghi Xuân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Thạch Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Vũ Quang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Huyện Lộc Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hà Tĩnh - Thị xã Kỳ Anh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Thành phố Hải Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Thành phố Chí Linh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Bình Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Cẩm Giàng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Gia Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Kim Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Thị xã Kinh Môn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Nam Sách', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Ninh Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Thanh Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Thanh Miện', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Dương - Huyện Tứ Kỳ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Quận Dương Kinh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Quận Đồ Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Quận Hải An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Quận Kiến An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Quận Hồng Bàng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Quận Ngô Quyền', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Quận Lê Chân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện An Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện An Lão', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện đảo Bạch Long Vĩ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện đảo Cát Hải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện Kiến Thụy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện Tiên Lãng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện Vĩnh Bảo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện Thủy Nguyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Thành phố Thủy Nguyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hải Phòng - Huyện An Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Thành phố Vị Thanh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Thành phố Ngã Bảy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Huyện Châu Thành A', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Huyện Long Mỹ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Huyện Phụng Hiệp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Huyện Vị Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hậu Giang - Thị Xã Long Mỹ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Thành phố Hòa Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Lương Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Cao Phong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Đà Bắc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Kim Bôi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Kỳ Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Lạc Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Lạc Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Mai Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Tân Lạc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hòa Bình - Huyện Yên Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Thành phố Hưng Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Ân Thi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Khoái Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Kim Động', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Thị xã Mỹ Hào', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Phù Cừ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Tiên Lữ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Văn Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Văn Lâm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hưng Yên - Huyện Yên Mỹ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Thành phố Nha Trang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Thành phố Cam Ranh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Huyện Vạn Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Thị xã Ninh Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Huyện Diên Khánh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Huyện Khánh Vĩnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Huyện Khánh Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Huyện Cam Lâm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Khánh Hòa - Huyện đảo Trường Sa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Thành phố Rạch Giá', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Thành phố Hà Tiên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện An Biên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện An Minh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Giồng Riềng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Gò Quao', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Hòn Đất', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Kiên Hải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Kiên Lương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Thành phố Phú Quốc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Tân Hiệp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Vĩnh Thuận', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện U Minh Thượng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kiên Giang - Huyện Giang Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Thành phố Kon Tum', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Đắk Glei', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Đắk Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Đắk Tô', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Kon Plông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Kon Rẫy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Ngọc Hồi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Sa Thầy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Tu Mơ Rông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Kon Tum - Huyện Ia H\' Drai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Thành phố Lai Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Huyện Mường Tè', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Huyện Phong Thổ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Huyện Sìn Hồ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Huyện Tam Đường', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Huyện Than Uyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Huyện Tân Uyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lai Châu - Huyện Nậm Nhùn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Thành phố Đà Lạt', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Thành phố Bảo Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Bảo Lâm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Cát Tiên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Di Linh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Đam Rông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Đạ Huoai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Đạ Tẻh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Đơn Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Lạc Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Lâm Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lâm Đồng - Huyện Đức Trọng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Thành phố Lạng Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Tràng Định', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Văn Lãng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Văn Quan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Bình Gia', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Bắc Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Hữu Lũng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Chi Lăng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Cao Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Lộc Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lạng Sơn - Huyện Đình Lập', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Thành phố Lào Cai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Bảo Thắng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Bảo Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Bát Xát', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Bắc Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Mường Khương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Sa Pa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Si Ma Cai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lào Cai - Huyện Văn Bàn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Thành phố Tân An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Bến Lức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Cần Đước', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Cần Giuộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Đức Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Đức Huệ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Mộc Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Tân Hưng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Tân Thạnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Tân Trụ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Thạnh Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Thủ Thừa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Huyện Vĩnh Hưng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Long An - Thị xã Kiến Tường', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Thành phố Nam Định', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Giao Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Hải Hậu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Mỹ Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Nam Trực', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Nghĩa Hưng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Trực Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Vụ Bản', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Xuân Trường', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nam Định - Huyện Ý Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Thành phố Vinh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Thị xã Cửa Lò', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Thị xã Thái Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Anh Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Con Cuông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Diễn Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Đô Lương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Hưng Nguyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Quỳ Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Kỳ Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Nam Đàn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Nghi Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Nghĩa Đàn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Quế Phong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Quỳ Hợp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Quỳnh Lưu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Tân Kỳ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Thanh Chương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Tương Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Huyện Yên Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nghệ An - Thị xã Hoàng Mai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Thành phố Ninh Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Thành phố Tam Điệp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Huyện Gia Viễn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Huyện Hoa Lư', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Huyện Kim Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Huyện Nho Quan', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Huyện Yên Khánh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Huyện Yên Mô', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Bình - Thành phố Hoa Lư', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Thuận - Thành phố Phan Rang – Tháp Chàm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Thuận - Huyện Bác Ái', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Thuận - Huyện Ninh Hải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Thuận - Huyện Ninh Phước', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Thuận - Huyện Ninh Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Thuận - Huyện Thuận Bắc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ninh Thuận - Huyện Thuận Nam', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Thành phố Việt Trì', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Thị xã Phú Thọ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Cẩm Khê', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Đoan Hùng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Hạ Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Lâm Thao', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Phù Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Tam Nông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Tân Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Thanh Ba', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Thanh Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Thanh Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Thọ - Huyện Yên Lập', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Thành phố Tuy Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Thị xã Sông Cầu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Thị xã Đông Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Huyện Đồng Xuân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Huyện Phú Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Huyện Sơn Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Huyện Sông Hinh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Huyện Tây Hòa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phú Yên - Huyện Tuy An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Thành Phố Đồng Hới', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Huyện Bố Trạch', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Huyện Lệ Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Huyện Minh Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Huyện Quảng Trạch', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Huyện Quảng Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Huyện Tuyên Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Bình - Thị xã Ba Đồn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Thành phố Tam Kỳ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Thành phố Hội An', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Thị xã Điện Bàn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Bắc Trà My', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Thăng Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Nam Trà My', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Núi Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Phước Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Tiên Phước', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Hiệp Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Nông Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Đông Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Nam Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Đại Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Phú Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Tây Giang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Duy Xuyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Nam - Huyện Quế Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Thành phố Quảng Ngãi', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Ba Tơ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Bình Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Thị xã Đức Phổ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Minh Long', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Mộ Đức', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Nghĩa Hành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Sơn Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Sơn Tây', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Sơn Tịnh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Tây Trà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Trà Bồng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện Tư Nghĩa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ngãi - Huyện đảo Lý Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Thành phố Hạ Long', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Thành phố Móng Cái', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Thành phố Cẩm Phả', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Thành phố Uông Bí', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Ba Chẽ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Bình Liêu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Cô Tô', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Đầm Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Thị xã Đông Triều', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Hải Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Hoành Bồ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Tiên Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Huyện Vân Đồn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Ninh - Thị xã Quảng Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Thành phố Đông Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Thị xã Quảng Trị', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Cam Lộ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Đảo Cồn Cỏ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Đa Krông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Gio Linh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Hải Lăng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Hướng Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Triệu Phong', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Quảng Trị - Huyện Vĩnh Linh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Thành phố Sóc Trăng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Cù Lao Dung', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Kế Sách', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Long Phú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Mỹ Tú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Mỹ Xuyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Thị xã Ngã Năm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Thạnh Trị', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Thị xã Vĩnh Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sóc Trăng - Huyện Trần Đề', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Thành phố Sơn La', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Quỳnh Nhai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Mường La', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Thuận Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Phù Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Bắc Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Mai Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Sông Mã', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Yên Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Mộc Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Sốp Cộp', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Sơn La - Huyện Vân Hồ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Thành phố Tây Ninh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Huyện Tân Biên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Huyện Tân Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Huyện Dương Minh Châu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Thị xã Hòa Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Huyện Bến Cầu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Huyện Gò Dầu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tây Ninh - Thị xã Trảng Bàng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Thành phố Thái Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Huyện Đông Hưng', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Huyện Hưng Hà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Huyện Kiến Xương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Huyện Quỳnh Phụ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Huyện Thái Thụy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Huyện Tiền Hải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Bình - Huyện Vũ Thư', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Thành phố Thái Nguyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Thành phố Sông Công', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Thị xã Phổ Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Huyện Phú Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Huyện Đồng Hỷ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Huyện Võ Nhai', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Huyện Định Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Huyện Đại Từ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thái Nguyên - Huyện Phú Lương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Thành phố Thanh Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Thị xã Bỉm Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Thành phố Sầm Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Bá Thước', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Cẩm Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Đông Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Hà Trung', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Hậu Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Hoằng Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Lang Chánh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Mường Lát', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Nga Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Ngọc Lặc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Như Thanh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Như Xuân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Nông Cống', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Quan Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Quan Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Quảng Xương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Thạch Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Thiệu Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Thọ Xuân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Thường Xuân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Tĩnh Gia', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Triệu Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Vĩnh Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Huyện Yên Định', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thanh Hóa - Thị Xã Nghi Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Thành phố Huế', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Thị xã Hương Thủy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Huyện A Lưới', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Thị xã Hương Trà', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Huyện Nam Đông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Huyện Phong Điền', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Huyện Phú Lộc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Huyện Phú Vang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Huyện Quảng Điền', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Quận Thuận Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Thị xã Phong Điền', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Thừa Thiên Huế - Quận Phú Xuân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Thành phố Mỹ Tho', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Thị xã Gò Công', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Gò Công Đông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Gò Công Tây', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Chợ Gạo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Tân Phước', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Thị xã Cai Lậy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Cái Bè', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Tân Phú Đông', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tiền Giang - Huyện Cai Lậy', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Thành phố Trà Vinh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Huyện Càng Long', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Huyện Châu Thành', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Huyện Cầu Kè', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Huyện Tiểu Cần', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Huyện Cầu Ngang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Huyện Trà Cú', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Huyện Duyên Hải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trà Vinh - Thị xã Duyên Hải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuyên Quang - Thành phố Tuyên Quang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuyên Quang - Huyện Chiêm Hóa', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuyên Quang - Huyện Hàm Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuyên Quang - Huyện Nà Hang', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuyên Quang - Huyện Sơn Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuyên Quang - Huyện Yên Sơn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Tuyên Quang - Huyện Lâm Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Thành phố Vĩnh Long', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Thị xã Bình Minh', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Huyện Bình Tân', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Huyện Long Hồ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Huyện Mang Thít', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Huyện Tam Bình', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Huyện Trà Ôn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Long - Huyện Vũng Liêm', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Thành phố Vĩnh Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Thành phố Phúc Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Huyện Bình Xuyên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Huyện Lập Thạch', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Huyện Sông Lô', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Huyện Tam Dương', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Huyện Tam Đảo', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Huyện Vĩnh Tường', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vĩnh Phúc - Huyện Yên Lạc', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Thành phố Yên Bái', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Thị xã Nghĩa Lộ', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Huyện Lục Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Huyện Mù Căng Chải', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Huyện Trấn Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Huyện Trạm Tấu', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Huyện Văn Chấn', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Huyện Văn Yên', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Yên Bái - Huyện Yên Bình', 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
