<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('districts')->insert([
//            ['name' => 'An Giang'],
            ['province_id' => 1, 'name' => 'Châu Đốc'],
            ['province_id' => 1, 'name' => 'Long Xuyên'],
            ['province_id' => 1, 'name' => 'Tân Châu'],
            ['province_id' => 1, 'name' => 'Châu Thành'],
            ['province_id' => 1, 'name' => 'Phú Tân'],
            ['province_id' => 1, 'name' => 'Chợ Mới'],
            ['province_id' => 1, 'name' => 'Thoại Sơn'],
            ['province_id' => 1, 'name' => 'Tịnh Biên'],
            ['province_id' => 1, 'name' => 'Tri Tôn'],
            ['province_id' => 1, 'name' => 'An Phú'],
//            ['name' => 'Bà Rịa - Vũng Tàu'],
            ['province_id' => 2, 'name' => 'Vũng Tàu'],
            ['province_id' => 2, 'name' => 'Bà Rịa'],
            ['province_id' => 2, 'name' => 'Long Điền'],
            ['province_id' => 2, 'name' => 'Đất Đỏ'],
            ['province_id' => 2, 'name' => 'Xuyên Mộc'],
            ['province_id' => 2, 'name' => 'Châu Đức'],
            ['province_id' => 2, 'name' => 'Tân Thành'],
            ['province_id' => 2, 'name' => 'Côn Đảo'],
//            ['name' => 'Bắc Giang'],
            ['province_id' => 3, 'name' => 'Bắc Giang'],
            ['province_id' => 3, 'name' => 'Lạng Giang'],
            ['province_id' => 3, 'name' => 'Yên Thế'],
            ['province_id' => 3, 'name' => 'Việt Yên'],
            ['province_id' => 3, 'name' => 'Hiệp Hòa'],
            ['province_id' => 3, 'name' => 'Tân Yên'],
            ['province_id' => 3, 'name' => 'Sơn Động'],
            ['province_id' => 3, 'name' => 'Lục Nam'],
            ['province_id' => 3, 'name' => 'Lục Ngạn'],
//            ['name' => 'Bắc Kạn'],
            ['province_id' => 4, 'name' => 'Bắc Kạn'],
            ['province_id' => 4, 'name' => 'Chợ Mới'],
            ['province_id' => 4, 'name' => 'Ngân Sơn'],
            ['province_id' => 4, 'name' => 'Ba Bể'],
            ['province_id' => 4, 'name' => 'Pác Nặm'],
            ['province_id' => 4, 'name' => 'Bạch Thông'],
            ['province_id' => 4, 'name' => 'Cao Kỳ'],
            ['province_id' => 4, 'name' => 'Chí Linh'],
//            ['name' => 'Bạc Liêu'],
            ['province_id' => 5, 'name' => 'Bạc Liêu'],
            ['province_id' => 5, 'name' => 'Hồng Dân'],
            ['province_id' => 5, 'name' => 'Phước Long'],
            ['province_id' => 5, 'name' => 'Vĩnh Lợi'],
            ['province_id' => 5, 'name' => 'Giá Rai'],
            ['province_id' => 5, 'name' => 'Đông Hải'],
            ['province_id' => 5, 'name' => 'Hoà Bình'],
            ['province_id' => 5, 'name' => 'Tuy Hòa'],
//            ['name' => 'Bắc Ninh'],
            ['province_id' => 6, 'name' => 'Bắc Ninh'],
            ['province_id' => 6, 'name' => 'Gia Bình'],
            ['province_id' => 6, 'name' => 'Lương Tài'],
            ['province_id' => 6, 'name' => 'Thuận Thành'],
            ['province_id' => 6, 'name' => 'Tiên Du'],
            ['province_id' => 6, 'name' => 'Yên Phong'],
            ['province_id' => 6, 'name' => 'Quế Võ'],
            ['province_id' => 6, 'name' => 'Từ Sơn'],
//            ['name' => 'Bến Tre'],
            ['province_id' => 7, 'name' => 'Bến Tre'],
            ['province_id' => 7, 'name' => 'Châu Thành'],
            ['province_id' => 7, 'name' => 'Chợ Lách'],
            ['province_id' => 7, 'name' => 'Ba Tri'],
            ['province_id' => 7, 'name' => 'Mỏ Cày Bắc'],
            ['province_id' => 7, 'name' => 'Mỏ Cày Nam'],
            ['province_id' => 7, 'name' => 'Gò Công Tây'],
            ['province_id' => 7, 'name' => 'Gò Công Đông'],
            ['province_id' => 7, 'name' => 'Thạnh Phú'],
            ['province_id' => 7, 'name' => 'Bình Đại'],
//            ['name' => 'Bình Định'],
            ['province_id' => 8, 'name' => 'Qui Nhơn'],
            ['province_id' => 8, 'name' => 'An Lão'],
            ['province_id' => 8, 'name' => 'Hoài Nhơn'],
            ['province_id' => 8, 'name' => 'Phù Cát'],
            ['province_id' => 8, 'name' => 'Tây Sơn'],
            ['province_id' => 8, 'name' => 'Vân Canh'],
            ['province_id' => 8, 'name' => 'Bình Khê'],
            ['province_id' => 8, 'name' => 'Tuy Phước'],
            ['province_id' => 8, 'name' => 'Hoài Ân'],
            ['province_id' => 8, 'name' => 'Krông Pa'],
//            ['name' => 'Bình Dương'],
            ['province_id' => 9, 'name' => 'Thủ Dầu Một'],
            ['province_id' => 9, 'name' => 'Bến Cát'],
            ['province_id' => 9, 'name' => 'Dĩ An'],
            ['province_id' => 9, 'name' => 'Thuận An'],
            ['province_id' => 9, 'name' => 'Tân Uyên'],
            ['province_id' => 9, 'name' => 'Phú Giáo'],
            ['province_id' => 9, 'name' => 'Bàu Bàng'],
            ['province_id' => 9, 'name' => 'Vĩnh Cửu'],
            ['province_id' => 9, 'name' => 'Củ Chi'],
//            ['name' => 'Bình Phước'],
            ['province_id' => 10, 'name' => 'Đồng Xoài'],
            ['province_id' => 10, 'name' => 'Phước Long'],
            ['province_id' => 10, 'name' => 'Bình Long'],
            ['province_id' => 10, 'name' => 'Chơn Thành'],
            ['province_id' => 10, 'name' => 'Bù Đăng'],
            ['province_id' => 10, 'name' => 'Bù Gia Mập'],
            ['province_id' => 10, 'name' => 'Lộc Ninh'],
            ['province_id' => 10, 'name' => 'Hớn Quản'],
            ['province_id' => 10, 'name' => 'Tân Lập'],
//            ['name' => 'Bình Thuận'],
            ['province_id' => 11, 'name' => 'Phan Thiết'],
            ['province_id' => 11, 'name' => 'La Gi'],
            ['province_id' => 11, 'name' => 'Tánh Linh'],
            ['province_id' => 11, 'name' => 'Hàm Thuận Bắc'],
            ['province_id' => 11, 'name' => 'Hàm Thuận Nam'],
            ['province_id' => 11, 'name' => 'Đức Linh'],
            ['province_id' => 11, 'name' => 'Bắc Bình'],
            ['province_id' => 11, 'name' => 'Tuy Phong'],
            ['province_id' => 11, 'name' => 'Phú Quý'],
//            ['name' => 'Cà Mau'],
            ['province_id' => 12, 'name' => 'Cà Mau'],
            ['province_id' => 12, 'name' => 'Kinh Hải'],
            ['province_id' => 12, 'name' => 'Phú Tân'],
            ['province_id' => 12, 'name' => 'Đầm Dơi'],
            ['province_id' => 12, 'name' => 'Năm Căn'],
            ['province_id' => 12, 'name' => 'Trần Văn Thời'],
            ['province_id' => 12, 'name' => 'U Minh'],
            ['province_id' => 12, 'name' => 'Thới Bình'],
            ['province_id' => 12, 'name' => 'Cái Nước'],
//            ['name' => 'Cần Thơ'],
            ['province_id' => 13, 'name' => 'Cái Răng'],
            ['province_id' => 13, 'name' => 'Ninh Kiều'],
            ['province_id' => 13, 'name' => 'Ô Môn'],
            ['province_id' => 13, 'name' => 'Bình Thủy'],
            ['province_id' => 13, 'name' => 'Thốt Nốt'],
            ['province_id' => 13, 'name' => 'Vĩnh Thạnh'],
            ['province_id' => 13, 'name' => 'Cờ Đỏ'],
            ['province_id' => 13, 'name' => 'Phong Điền'],
            ['province_id' => 13, 'name' => 'Thới Lai'],
            ['province_id' => 13, 'name' => 'Kênh Xáng'],
//            ['name' => 'Cao Bằng'],
            ['province_id' => 14, 'name' => 'Thành phố Cao Bằng'],
            ['province_id' => 14, 'name' => 'Bảo Lâm'],
            ['province_id' => 14, 'name' => 'Bảo Lạc'],
            ['province_id' => 14, 'name' => 'Hạ Lang'],
            ['province_id' => 14, 'name' => 'Quảng Uyên'],
            ['province_id' => 14, 'name' => 'Phục Hòa'],
            ['province_id' => 14, 'name' => 'Nguyên Bình'],
            ['province_id' => 14, 'name' => 'Thạch An'],
            ['province_id' => 14, 'name' => 'Trùng Khánh'],
//            ['name' => 'Đà Nẵng'],
            ['province_id' => 15, 'name' => 'Hải Châu'],
            ['province_id' => 15, 'name' => 'Thanh Khê'],
            ['province_id' => 15, 'name' => 'Liên Chiểu'],
            ['province_id' => 15, 'name' => 'Cẩm Lệ'],
            ['province_id' => 15, 'name' => 'Sơn Trà'],
            ['province_id' => 15, 'name' => 'Ngũ Hành Sơn'],
            ['province_id' => 15, 'name' => 'Hoà Vang'],
            ['province_id' => 15, 'name' => 'Cù Lao Chàm'],
//            ['name' => 'Đắk Lắk'],
            ['province_id' => 16, 'name' => 'Buôn Ma Thuột'],
            ['province_id' => 16, 'name' => 'Ea H’Leo'],
            ['province_id' => 16, 'name' => 'Krông Búk'],
            ['province_id' => 16, 'name' => 'Krông Ana'],
            ['province_id' => 16, 'name' => 'Krông Năng'],
            ['province_id' => 16, 'name' => 'Ea Súp'],
            ['province_id' => 16, 'name' => 'Cư M’gar'],
            ['province_id' => 16, 'name' => 'Lắk'],
            ['province_id' => 16, 'name' => 'Buôn Đôn'],
            ['province_id' => 16, 'name' => 'M’Đrắk'],
//            ['name' => 'Đắk Nông'],
            ['province_id' => 17, 'name' => 'Gia Nghĩa'],
            ['province_id' => 17, 'name' => 'Đắk R’lấp'],
            ['province_id' => 17, 'name' => 'Đắk Mil'],
            ['province_id' => 17, 'name' => 'Cư Jút'],
            ['province_id' => 17, 'name' => 'Đắk Song'],
            ['province_id' => 17, 'name' => 'Krông Nô'],
            ['province_id' => 17, 'name' => 'Tuy Đức'],
//            ['name' => 'Điện Biên'],
            ['province_id' => 18, 'name' => 'Điện Biên Phủ'],
            ['province_id' => 18, 'name' => 'Mường Lay'],
            ['province_id' => 18, 'name' => 'Mường Chà'],
            ['province_id' => 18, 'name' => 'Mường Nhé'],
            ['province_id' => 18, 'name' => 'Tủa Chùa'],
            ['province_id' => 18, 'name' => 'Điện Biên Đông'],
            ['province_id' => 18, 'name' => 'Tuần Giáo'],
//            ['name' => 'Đồng Nai'],
            ['province_id' => 19, 'name' => 'Biên Hòa'],
            ['province_id' => 19, 'name' => 'Long Khánh'],
            ['province_id' => 19, 'name' => 'Nhơn Trạch'],
            ['province_id' => 19, 'name' => 'Vĩnh Cửu'],
            ['province_id' => 19, 'name' => 'Định Quán'],
            ['province_id' => 19, 'name' => 'Tân Phú'],
            ['province_id' => 19, 'name' => 'Trảng Bom'],
            ['province_id' => 19, 'name' => 'Cẩm Mỹ'],
//            ['name' => 'Đồng Tháp'],
            ['province_id' => 20, 'name' => 'Sa Đéc'],
            ['province_id' => 20, 'name' => 'Cao Lãnh'],
            ['province_id' => 20, 'name' => 'Hồng Ngự'],
            ['province_id' => 20, 'name' => 'Tam Nông'],
            ['province_id' => 20, 'name' => 'Tân Hồng'],
            ['province_id' => 20, 'name' => 'Lai Vung'],
            ['province_id' => 20, 'name' => 'Châu Thành'],
//            ['name' => 'Gia Lai'],
            ['province_id' => 21, 'name' => 'Pleiku'],
            ['province_id' => 21, 'name' => 'An Khê'],
            ['province_id' => 21, 'name' => 'Ayun Pa'],
            ['province_id' => 21, 'name' => 'Kông Chro'],
            ['province_id' => 21, 'name' => 'Chư Păh'],
            ['province_id' => 21, 'name' => 'Chư Sê'],
            ['province_id' => 21, 'name' => 'Đăk Đoa'],
            ['province_id' => 21, 'name' => 'Kbang'],
//            ['name' => 'Hà Giang'],
            ['province_id' => 22, 'name' => 'Hà Giang'],
            ['province_id' => 22, 'name' => 'Quản Bạ'],
            ['province_id' => 22, 'name' => 'Yên Minh'],
            ['province_id' => 22, 'name' => 'Vị Xuyên'],
            ['province_id' => 22, 'name' => 'Bắc Mê'],
            ['province_id' => 22, 'name' => 'Hoàng Su Phì'],
            ['province_id' => 22, 'name' => 'Mèo Vạc'],
            ['province_id' => 22, 'name' => 'Đồng Văn'],
            ['province_id' => 22, 'name' => 'Bắc Quang'],
            ['province_id' => 22, 'name' => 'Việt Lâm'],
//            ['name' => 'Hà Nam'],
//            ['name' => 'Hà Nội'],
            ['province_id' => 24, 'name' => 'Ba Đình'],
            ['province_id' => 24, 'name' => 'Hoàn Kiếm'],
            ['province_id' => 24, 'name' => 'Tây Hồ'],
            ['province_id' => 24, 'name' => 'Long Biên'],
            ['province_id' => 24, 'name' => 'Cầu Giấy'],
            ['province_id' => 24, 'name' => 'Đống Đa'],
            ['province_id' => 24, 'name' => 'Hai Bà Trưng'],
            ['province_id' => 24, 'name' => 'Thanh Xuân'],
            ['province_id' => 24, 'name' => 'Hoàng Mai'],
            ['province_id' => 24, 'name' => 'Nam Từ Liêm'],
            ['province_id' => 24, 'name' => 'Bắc Từ Liêm'],
//            ['name' => 'Hà Tĩnh'],
//            ['name' => 'Hải Dương'],
//            ['name' => 'Hải Phòng'],
//            ['name' => 'Hậu Giang'],
//            ['name' => 'Hòa Bình'],
//            ['name' => 'Hưng Yên'],
//            ['name' => 'Khánh Hòa'],
//            ['name' => 'Kiên Giang'],
//            ['name' => 'Kon Tum'],
//            ['name' => 'Lai Châu'],
//            ['name' => 'Lâm Đồng'],
//            ['name' => 'Lạng Sơn'],
//            ['name' => 'Lào Cai'],
//            ['name' => 'Long An'],
//            ['name' => 'Nam Định'],
//            ['name' => 'Nghệ An'],
//            ['name' => 'Ninh Bình'],
//            ['name' => 'Ninh Thuận'],
//            ['name' => 'Phú Thọ'],
//            ['name' => 'Phú Yên'],
//            ['name' => 'Quảng Bình'],
//            ['name' => 'Quảng Nam'],
//            ['name' => 'Quảng Ngãi'],
//            ['name' => 'Quảng Ninh'],
//            ['name' => 'Quảng Trị'],
//            ['name' => 'Sóc Trăng'],
//            ['name' => 'Sơn La'],
//            ['name' => 'Tây Ninh'],
//            ['name' => 'Thái Bình'],
//            ['name' => 'Thái Nguyên'],
//            ['name' => 'Thanh Hóa'],
//            ['name' => 'Thừa Thiên Huế'],
//            ['name' => 'Tiền Giang'],
//            ['name' => 'TP Hồ Chí Minh'],
            ['province_id' => 58, 'name' => 'Quận 1'],
            ['province_id' => 58, 'name' => 'Quận 2'],
            ['province_id' => 58, 'name' => 'Quận 3'],
            ['province_id' => 58, 'name' => 'Quận 4'],
            ['province_id' => 58, 'name' => 'Quận 5'],
            ['province_id' => 58, 'name' => 'Quận 6'],
            ['province_id' => 58, 'name' => 'Quận 7'],
            ['province_id' => 58, 'name' => 'Quận 8'],
            ['province_id' => 58, 'name' => 'Quận 9'],
            ['province_id' => 58, 'name' => 'Quận 10'],
            ['province_id' => 58, 'name' => 'Quận 11'],
            ['province_id' => 58, 'name' => 'Quận 12'],
            ['province_id' => 58, 'name' => 'Bình Thạnh'],
            ['province_id' => 58, 'name' => 'Gò Vấp'],
            ['province_id' => 58, 'name' => 'Tân Bình'],
            ['province_id' => 58, 'name' => 'Tân Phú'],
            ['province_id' => 58, 'name' => 'Phú Nhuận'],
            ['province_id' => 58, 'name' => 'Bình Tân'],
            ['province_id' => 58, 'name' => 'Hóc Môn'],
            ['province_id' => 58, 'name' => 'Củ Chi'],
            ['province_id' => 58, 'name' => 'Nhà Bè'],
            ['province_id' => 58, 'name' => 'Cần Giờ'],
//            ['name' => 'Trà Vinh'],
//            ['name' => 'Tuyên Quang'],
//            ['name' => 'Vĩnh Long'],
//            ['name' => 'Vĩnh Phúc'],
//            ['name' => 'Yên Bái'],
        ]);
    }
}
